spring:
    profiles:
      active: dev
---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: mc-config-dev
---
server:
  port: 4002
spring:
  profiles: prod
  application:
    name: mc-config-prod